name: Cut release branch

on:
  schedule:
    # 17:00 UTC on the 25th of each month
    - cron: '0 17 25 * *'
  workflow_dispatch:
    inputs:
      ref:
        description: 'Commit or branch to release'
        required: true
        default: 'master'
      version:
        description: 'Version number for the release (optional)'
        required: false
        default: ''

permissions:
  contents: write
  pull-requests: write

jobs:
  cut-release-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.event.inputs.ref || 'master' }}

      - name: Set up environment
        uses: ./.github/actions/setup
        with:
          download-translations: 'false'

      - name: Bump package versions
        id: bump_package_versions
        shell: bash
        env:
          INPUT_VERSION: ${{ github.event.inputs.version }}
        run: |
          declare -A packages=(
            [web]="desktop-client"
            [electron]="desktop-electron"
            [sync]="sync-server"
            [api]="api"
            [cli]="cli"
            [core]="loot-core"
          )

          for key in "${!packages[@]}"; do
            pkg="${packages[$key]}"

            if [[ -n "$INPUT_VERSION" ]]; then
              version=$(yarn workspace @actual-app/ci-actions tsx bin/get-next-package-version.ts \
                --package-json "./packages/$pkg/package.json" \
                --version "$INPUT_VERSION" \
                --update)
            else
              version=$(yarn workspace @actual-app/ci-actions tsx bin/get-next-package-version.ts \
                --package-json "./packages/$pkg/package.json" \
                --type monthly \
                --update)
            fi

            eval "NEW_${key^^}_VERSION=\"$version\""
          done

          echo "version=$NEW_WEB_VERSION" >> "$GITHUB_OUTPUT"

      - name: Create release branch and PR
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          token: ${{ secrets.ACTIONS_UPDATE_TOKEN }}
          commit-message: '🔖 (${{ steps.bump_package_versions.outputs.version }})'
          title: '🔖 (${{ steps.bump_package_versions.outputs.version }})'
          body: 'Generated by [cut-release-branch.yml](../tree/master/.github/workflows/cut-release-branch.yml)'
          branch: 'release/v${{ steps.bump_package_versions.outputs.version }}'
          base: master
